### ISSUE TITLE
Django3: render_to_response is deprecated

### ISSUE THREAD

**Issue by gozer** [fireantology/django-logtailer#11]
https://docs.djangoproject.com/en/2.2/releases/2.0/#id1

> django.shortcuts.render_to_response() is deprecated in favor of django.shortcuts.render(). 
> render() takes the same arguments except that it also requires a request.

**Comment by fireantology** [comment]
Thanks. Will change it in the next release

**Comment by sadikekin** [comment]
Please check https://github.com/fireantology/django-logtailer/pull/12

**Comment by fireantology** [comment]
Merged, gonna be in next release
