### ISSUE TITLE
LOGTAILER_HISTORY_LINES should be a paramater manageble from the interface

### ISSUE THREAD

**Issue by sadikekin** [fireantology/django-logtailer#13]
I think to change the last lines that we want is not very effective in the settings file. WE should be able to change this by using the model parameter.

**Comment by fireantology** [comment]
Hi,
My idea is to have it as input parameter on the form and that could be changed prior to start reading the file for the first time and then keep it read only till you don't close the page.

**Comment by sadikekin** [comment]
That is really good idea. What should I do if I want to read the whole document. Do you think is it logical to add a parameter to the model?

**Comment by fireantology** [comment]
I would avoid reading the full document, can be a problem when working on really big log files.
I will add a form field with a free number so that you can still go several lines back, I think is flexible enough for most use cases.
