### ISSUE TITLE
add this package to pypi

### ISSUE THREAD

**Issue by MaorRayzin** [fireantology/django-logtailer#5]
Hey guys (or girls), this pckge is wonderful but I cannot use this in my code until it can be managed with PIP.
Please, this will help me a lot!

**Comment by fireantology** [comment]
Roger that. Working on it. Come back in one week

**Comment by MaorRayzin** [comment]
Thats great man!! thanks a lot!

**Comment by fireantology** [comment]
Done

**Comment by MaorRayzin** [comment]
Fantastic man!
