### ISSUE TITLE
io.UnsupportedOperation: can't do nonzero end-relative seeks

### ISSUE THREAD

**Issue by omarbenhamid** [fireantology/django-logtailer#9]
I have this issue when I activate history (when I set LOGTAILER_HISTORY_LINES to something not 0).

According to [this post](https://stackoverflow.com/questions/21533391/seeking-from-end-of-file-throwing-unsupported-exception) it could be because logtailer opens files in text mode. It should be fixed by adding "b" flag to the open() call so that log files are open in binary mode.

**Comment by fireantology** [comment]
Fixed in latest release 1.1
